<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?php $this->partial('user/sidebar'); ?>
        </div>
        <form method="post" class="col-md-9">
            <div class="page-header">
                <div class="pull-right">
                    <button class="btn btn-primary">Save</button>
                </div>
                <h3><?= $user->fullname ?>'s Password</h3>
            </div>
            
            <?php if($saved): ?>
            <div class="alert alert-success">
                <strong>Success!</strong> User password updated.
            </div>
            <?php endif; ?>
            
            <div class="row">
                <div class="col-md-6">
                    <?= $this->form->field('new_password'); ?>
                    <?= $this->form->field('retype_password'); ?>
                    <hr>
                    <?= $this->form->field('truncate_session'); ?>
                </div>
            </div>
            
        </form>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>