<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?php $this->partial('user/sidebar'); ?>
        </div>
        <form method="post" class="col-md-9">
            <div class="page-header">
                <?php if(!$readonly): ?>
                <div class="pull-right">
                    <button class="btn btn-primary">Save</button>
                </div>
                <?php endif; ?>
                <h3><?= $user->fullname ?>'s Permissions</h3>
            </div>
            
            <?php if($success): ?>
            <div class="alert alert-success">
                <strong>Success!</strong> User permissions updated.
            </div>
            <?php endif; ?>
            
            
            <?php if($all_roles && !$readonly): ?>
            <div class="text-right">
                <div class="btn-group btn-group-xs" role="group">
                    <button class="btn btn-default role-unselector" type="button" title="Select none">
                        <i class="fa fa-square-o" aria-hidden="true"></i> Unselect All
                    </button>
                </div>
                <div class="btn-group btn-group-xs" role="group">
                    <?php foreach($all_roles as $role): ?>
                    <button class="btn btn-default role-selector" data-role="<?= $role ?>" type="button" title="Select all <?= $role ?> role">
                        <i class="fa fa-check-square-o" aria-hidden="true"></i> <?= $role ?>
                    </button>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php endif; ?>
            
            <?php if($readonly): ?>
                <div class="alert alert-info">
                    Current user using <code>role</code> for permission filters.
                </div>
            <?php endif; ?>
            
            <?php if($grouped_perms): ?>
                <?php foreach($grouped_perms as $group => $perms): ?>
                    <?php $id = md5($group); ?>
                <h4>
                    <?php if(!$readonly): ?>
                        <div class="btn-group btn-group-xs">
                            <button class="btn btn-default group-selector" data-target="#group-<?= $id ?>" title="Select All" type="button"><i class="fa fa-check-square-o" aria-hidden="true"></i></button>
                            <button class="btn btn-default group-unselector" data-target="#group-<?= $id ?>" title="Unselect All" type="button"><i class="fa fa-square-o" aria-hidden="true"></i></button>
                        </div>
                    <?php endif; ?>
                    <?= $group ?>
                </h4>
                <table class="table table-hover" id="group-<?= $id ?>">
                    <tbody>
                        <?php foreach($perms as $perm): ?>
                        <tr>
                            <td>
                            <div class="checkbox checkbox-plain">
                                <input type="checkbox" class="item-checkbox" name="<?= $perm->name ?>" id="perm-<?= $perm->id ?>" data-group="<?= $perm->group ?>" data-role="<?= $perm->role ?>"<?= (in_array($perm->id, $user_perms)?' checked="checked"':'') ?><?= ($readonly?' disabled="disabled"':'') ?>>
                                <label for="perm-<?= $perm->id ?>"><?= $perm->name ?></label>
                            </div>
                            </td>
                            <td><?= $perm->about ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endforeach; ?>
            <?php endif; ?>
            
        </form>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>